import Head from 'next/head';
import React from 'react';
import { FaCss3, FaGithub, FaJs, FaReact } from 'react-icons/fa';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { waveimg } from "./../../public/devimg.png";
import web1 from '../../public/web1.png';


export default function Home() {
  return (
    <>
      <Head>
        <title>Shrish Kerur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='px-4 min-h-screen md:px-16'>
        <section className='px-3'>
          <nav className='py-10 flex justify-between items-center'>
            <h3 className='text-2xl text-gray-700 font-medium md:text-4xl'>Shrish Kerur</h3>

            <ul className='flex items-center text-lg'>
              <li className='mx-8 md:mx-12'><BsFillMoonStarsFill /></li>
              <li><a className='bg-teal-500 text-gray-800 px-3 py-1 rounded-md md:px-6 md:py-3' href='#'>Resume</a></li>
            </ul>
          </nav>
        </section>



        <section className='px-3 py-16 h-full text-center md:flex md:justify-center md:items-center'>
          <div className='text-center md:text-left md:w-3/5'>
            <h2 className='my-3 text-4xl md:text-5xl'>Hai I am Shrish</h2>
            <span className='text-2xl text-teal-700 font-medium md:text-3xl'>A Front End Developer</span>
            <p className='my-8 text-xl md:text-2xl'>Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
          </div>

            <div className='py-6 md:w-2/5 md:h-full md:px-10'>
              <img className='h-96 w-96 border-2 border-black border-solid' src={web1} alt='img'></img>
            </div>
        </section>




        <section className='px-3 py-16 h-full text-center'>
          <div className='my-12'>
            <h3 className='mx-auto py-4 text-4xl text-teal-700 font-medium md:text-6xl'>Services</h3>
          </div>

          <div className='py-2 grid grid-cols-2 grid-rows-2 gap-8 md:grid-cols-4 md:gap-24'>
            <div className='px-4 mx-auto w-46 h-32 text-2xl'><FaJs size={90} />JavaScript</div>
            <div className='px-4 mx-auto w-46 h-32 text-2xl'><FaReact size={90} />React</div>
            <div className='px-4 mx-auto w-46 h-32 text-2xl'><FaCss3 size={90} />CSS</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl'><FaGithub size={90} />GitHub</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl'><FaGithub size={90} />GitHub</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl'><FaGithub size={90} />GitHub</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl'><FaGithub size={90} />GitHub</div>
            <div className='px-4 mx-auto w-46 h-fu32 text-2xl'><FaGithub size={90} />GitHub</div>
          </div>

        </section>

        <section className='px-3 py-16 h-full text-center'>
            <div className='mx-auto my-6'>
              <h3 className='text-4xl text-teal-700 font-medium md:text-6xl md:py-4'>Work</h3>
            </div>

          <div className='grid grid-cols-1 gap-8 md:grid-cols-2 md:justify-items-center'>

            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12'>
              <div></div>
              <span className='text-3xl text-gray-800 font-semibold'>Portfolio Project</span>
            </div>

            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12'>
              <div></div>
              <span className='text-3xl text-gray-800 font-semibold'>E-Commerce Project</span>
            </div>

            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12'>
              <div></div>
              <span className='text-3xl text-gray-800 font-semibold'>Personal Landing Page</span>
            </div>

            <div className='w-full h-64 bg-teal-200 flex flex-col justify-center items-center rounded-2xl md:w-10/12'>
              <div></div>
              <span className='text-3xl text-gray-800 font-semibold'>To-Do App</span>
            </div>

          </div>
        </section>


      <section className='px-3 py-16 text-center'>
        <div className='w-full md:w-3/5 md:mx-auto'>

          <h3 className='mx-auto my-12 text-4xl text-teal-600 font-medium md:text-6xl'>Say a Hai</h3>

          <div>
            <form action='https://getform.io/f/c4401388-b490-4748-a9ce-0d431669dbe4' method='POST'>
            
            <div className='flex flex-col-reverse justify-center items-baseline text-2xl md:py-4'>
                <input name='name' className='my-2 px-4 py-3 w-full rounded-lg bg-teal-200 md:h-12' type={'text'} /><span className='text-2xl px-3 md:text-3xl'>Name</span>
            </div>
            
            <div className='flex flex-col-reverse justify-center items-baseline text-2xl md:py-4'>
                <input name='email' className='my-2 px-4 py-2 w-full rounded-lg bg-teal-200 md:h-12' type={'email'} /><span className='text-2xl px-3 md:text-3xl'>Email</span>
            </div>
            
            <div className='flex flex-col-reverse justify-center items-baseline text-2xl md:py-4'>
                <textarea name='comment' className='my-2 px-4 py-2 w-full rounded-lg bg-teal-200 h-64' type={'text'} /><span className='text-2xl px-3 md:text-3xl'>Comment</span>
            </div>
            
            <div>
              <button className='my-8 px-8 py-4 text-3xl bg-teal-400 border-none rounded-lg'>Submit</button>
            </div>
            
            </form>
          </div>

          <div className='w-full mx-auto my-10'>
            <h2 className='text-4xl text-teal-600 md:text-7xl'>Thank You 🙏</h2>
          </div>
          
        </div>
      </section>

      </main>
    </>
  );
}
