import Head from 'next/head';
import React from 'react';
import { FaAtom, FaCss3, FaGit, FaGithub, FaHtml5, FaJs, FaPython, FaReact } from 'react-icons/fa';
import { SiTailwindcss } from 'react-icons/si';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import Image from 'next/legacy/image';
import devimg from './../../public/assets/devimg.png'
import { useState } from 'react';
import flip1 from './../../public/ecommerce/flip1.png';
import Header from '@/components/Header';
import Intro from '@/components/Intro';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Shrish Kerur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/profile/unnamed.jpg" />
      </Head>
      <body>
        <header className='w-full h-auto py-3 mx-auto
        '>
          <Header />
        </header>
        <main className='w-full h-auto py-3 mx-auto'>
          <Intro />
        </main>
        <footer className='w-full h-40'>

        </footer>
      </body>
    </div>
  );
}
